spring:
  application:
    name: web-quiz

  datasource:
    url: jdbc:h2:mem:~/webQuiz
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles:
    default: local

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


---
spring:
  config:
    activate:
      on-profile: test

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

